version: "3"
networks:
  gitea:
    driver: bridge
services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      # --- Existing Variables ---
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=$(openssl rand -hex 32)
      - GITEA__server__ROOT_URL=https://${DOMAIN}
      - GITEA__server__SSH_DOMAIN=${DOMAIN}
      - GITEA__server__SSH_PORT=22
      - GITEA__security__ADMIN_USER=${GITEA_ADMIN_USER}
      - GITEA__security__ADMIN_PASSWORD=${GITEA_ADMIN_PASSWORD}

      # --- Hardening Configurations ---
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__other__SHOW_FOOTER_VERSION=false
      - GITEA__repository__DEFAULT_PRIVATE=true
      - GITEA__security__COOKIE_SECURE=true
      - GITEA__security__COOKIE_HTTP_ONLY=true
      - GITEA__security__COOKIE_SAME_SITE=Strict
      
      # --- Optional: Disable unneeded features ---
      - GITEA__repository__ENABLE_ISSUES=false
      - GITEA__repository__ENABLE_PULL_REQUESTS=false
      - GITEA__repository__ENABLE_WIKI=false
    networks:
      - gitea
    volumes:
      - ./gitea-data:/data
    ports:
      - "3001:3000"
      - "2222:22"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15
    container_name: gitea-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - gitea
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
